
(in-package :xlib)

(defmacro define-card8-abrev (name)
  `(define-accessor ,name (8)
     ((index) `(read-card8 ,index))
     ((index thing) `(write-card8 ,index ,thing))))

(defmacro define-card16-abrev (name)
  `(define-accessor ,name (16)
     ((index) `(read-card16 ,index))
     ((index thing) `(write-card16 ,index ,thing))))

(defmacro define-card32-abrev (name)
  `(define-accessor ,name (32)
     ((index) `(read-card32 ,index))
     ((index thing) `(write-card32 ,index ,thing))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (define-card16-abrev devicespec)
  (define-card8-abrev keycode)
  (define-card8-abrev keymask)

  (define-card16-abrev butmask)
  (define-card16-abrev vmodmask)

  (define-card16-abrev gbndetailmask)
  (define-card16-abrev devfeature)
  (define-card16-abrev feature)
  (define-card16-abrev idresult)
  (define-card16-abrev vmod)
  (define-card16-abrev idspec) 
  (define-card16-abrev devicespec)
  (define-card16-abrev behavior) 
  (define-card16-abrev mapdetails)
  (define-card32-abrev indicator)
  (define-card32-abrev name-detail)
  (define-card8-abrev belldetail)
  (define-card8-abrev msgdetail)
  (define-card8-abrev imflags) 
  (define-card8-abrev explicit)
  (define-card16-abrev eventtype) 
  (define-card16-abrev bellclassspec)
  (define-card16-abrev nkndetail)
  (define-card16-abrev statepart)
  (define-card32-abrev control)
  (define-card8-abrev cmdetail)
  (define-card16-abrev xidetail) 

  (define-card8-abrev group)

  (define-card8-abrev groups)
  (define-card8-abrev immodswhich)
  (define-card8-abrev imgroupswhich)
  (define-card8-abrev imflag)
  (define-card8-abrev bellclassresult)
  (define-card16-abrev axoption)
  (define-card32-abrev boolctrl)
  (define-card16-abrev mappart)
  (define-card16-abrev setmapflags) 
  (define-card16-abrev ledclassspec)
  (define-card16-abrev axndetail)
  (define-card32-abrev namedetail)
  (define-card32-abrev perclientflag))

(deftype devicespec () 'card8)
(deftype keycode () 'card8)
(deftype keymask () 'card8)
(deftype butmask () 'card16)
(deftype vmodmask () 'card16)
(deftype gbndetailmask () 'card16)
(deftype devfeature () 'card16)
(deftype feature () 'card16)
(deftype idresult () 'card16)
(deftype vmod () 'card16)
(deftype idspec () 'card16)
(deftype devicespec () 'card16)
(deftype behavior () 'card16)
(deftype mapdetails () 'card16)
(deftype indicator () 'card32)
(deftype name-detail () 'card32)
(deftype belldetail () 'card8)
(deftype msgdetail () 'card8)
(deftype imflags () 'card8)
(deftype explicit () 'card8)
(deftype eventtype () 'card16)
(deftype bellclassspec () 'card16)
(deftype nkndetail () 'card16)
(deftype statepart () 'card16)
(deftype control () 'card32)
(deftype cmdetail () 'card8)
(deftype xidetail () 'card16)
(deftype group () 'card8)
(deftype groups () 'card8)
(deftype immodswhich () 'card8)
(deftype imgroupswhich () 'card8)
(deftype imflag () 'card8)
(deftype bellclassresult () 'card8)
(deftype axoption () 'card16)
(deftype boolctrl () 'card32)
(deftype mappart () 'card16)
(deftype setmapflags () 'card16)
(deftype ledclassspec () 'card16)
(deftype axndetail () 'card16)
(deftype namedetail () 'card32)
(deftype perclientflag () 'card32)
